on: [push]

jobs:
  cross_build:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build for ${{ matrix.arch }}

    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
          - arch: armv7
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}
          run: |
            apt-get update && apt install -y gcc
            gcc -o linux-serial-test linux-serial-test.c

            if [[ $(echo $GITHUB_REF | grep -n refs/tags/v) ]]; then
              version=${GITHUB_REF/refs\/tags\//}
              echo "GITHUB_REF=${GITHUB_REF} VERSION=${version}"
              tar zcf linux-serial-test-${version}-linux-${{ matrix.arch }}.tar.gz linux-serial-test LICENSES/*
            fi

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux-serial-test*.tar.gz
